<%
'This function will change all of the BBCode
'into real smileys, also bold/italics/underline

Function BBCode(String)
	BBCode = Replace(String,":D","<img src='http://www.skylords.com/img/t/14.gif'  style='display:inline;' alt=':D'>")
	BBCode = Replace(BBCode,":]","<img src='http://www.skylords.com/img/t/1.gif'  style='display:inline;' alt=':]'>")
	BBCode = Replace(BBCode,":)","<img src='http://www.skylords.com/img/t/2.gif'  style='display:inline;' alt=':)'>")
        BBCode = Replace(BBCode,";)","<img src='http://www.skylords.com/img/t/5.gif'  style='display:inline;' alt=';)'>")
        BBCode = Replace(BBCode,":P","<img src='http://www.skylords.com/img/t/6.gif'  style='display:inline;' alt=':P'>")
	BBCode = Replace(BBCode,":(","<img src='http://www.skylords.com/img/t/3.gif'  style='display:inline;' alt=':('>")
	BBCode = Replace(BBCode,":[","<img src='http://www.skylords.com/img/t/12.gif'  style='display:inline;' alt=':['>")
	BBCode = Replace(BBCode,":S","<img src='http://www.skylords.com/img/t/11.gif'  style='display:inline;' alt=':S'>")
	BBCode = Replace(BBCode,"B)","<img src='http://www.skylords.com/img/t/13.gif'  style='display:inline;' alt='B)'>")
	BBCode = Replace(BBCode,"]:-(","<img src='http://www.skylords.com/img/t/7.gif'  style='display:inline;' alt=']:-('>")
	BBCode = Replace(BBCode,"]:-)","<img src='http://www.skylords.com/img/t/8.gif'  style='display:inline;' alt=']:-)'>")
	BBCode = Replace(BBCode,":O","<img src='http://www.skylords.com/img/t/9.gif'  style='display:inline;' alt=':O'>")
	
	BBCode = Replace(BBCode,":beer:","<img src='http://www.skylords.com/img/t/beer.gif'  style='display:inline;' alt=':beer:'>")
	BBCode = Replace(BBCode,":blackeye:","<img src='http://www.skylords.com/img/t/blackeye.gif'  style='display:inline;' alt=':blackeye:'>")
	BBCode = Replace(BBCode,":camp:","<img src='http://www.skylords.com/img/t/camp.gif'  style='display:inline;' alt=':camp:'>")
	BBCode = Replace(BBCode,":censored:","<img src='http://www.skylords.com/img/t/censored.gif'  style='display:inline;' alt=':censored:'>")
	BBCode = Replace(BBCode,":clap:","<img src='http://www.skylords.com/img/t/clap.gif'  style='display:inline;' alt=':clap:'>")
	BBCode = Replace(BBCode,":deer:","<img src='http://www.skylords.com/img/t/deer.gif'  style='display:inline;' alt=':deer:'>")
	BBCode = Replace(BBCode,":flower:","<img src='http://www.skylords.com/img/t/flower.gif'  style='display:inline;' alt=':flower:'>")
	BBCode = Replace(BBCode,":guns:","<img src='http://www.skylords.com/img/t/guns.gif'  style='display:inline;' alt=':guns:'>")
	BBCode = Replace(BBCode,":hellno:","<img src='http://www.skylords.com/img/t/hellno.gif'  style='display:inline;' alt=':hellno:'>")
	BBCode = Replace(BBCode,":help:","<img src='http://www.skylords.com/img/t/help.gif'  style='display:inline;' alt=':help:'>")
	BBCode = Replace(BBCode,":love:","<img src='http://www.skylords.com/img/t/love.gif'  style='display:inline;' alt=':love:'>")
	BBCode = Replace(BBCode,":out:","<img src='http://www.skylords.com/img/t/out.gif'  style='display:inline;' alt=':out:'>")
	BBCode = Replace(BBCode,":pray:","<img src='http://www.skylords.com/img/t/pray.gif'  style='display:inline;' alt=':pray:'>")
	BBCode = Replace(BBCode,":santa:","<img src='http://www.skylords.com/img/t/santa.gif'  style='display:inline;' alt=':santa:'>")
	BBCode = Replace(BBCode,":shh:","<img src='http://www.skylords.com/img/t/shh.gif'  style='display:inline;' alt=':shh:'>")
	BBCode = Replace(BBCode,":sleep:","<img src='http://www.skylords.com/img/t/sleep.gif'  style='display:inline;' alt=':sleep:'>")
	BBCode = Replace(BBCode,":stupid:","<img src='http://www.skylords.com/img/t/stupid.gif'  style='display:inline;' alt=':stupid:'>")
	BBCode = Replace(BBCode,":uzi:","<img src='http://www.skylords.com/img/t/uzi.gif'  style='display:inline;' alt=':uzi:'>")
	BBCode = Replace(BBCode,":whistle:","<img src='http://www.skylords.com/img/t/whistle.gif'  style='display:inline;' alt=':whistle:'>")
	BBCode = Replace(BBCode,":worthy:","<img src='http://www.skylords.com/img/t/worthy.gif'  style='display:inline;' alt=':worthy:'>")
	BBCode = Replace(BBCode,":monkey:","<img src='http://www.skylords.com/img/t/monkey.gif'  style='display:inline;' alt=':monkey:'>")
	BBCode = Replace(BBCode,":mouse:","<img src='http://www.skylords.com/img/t/mouse.gif'  style='display:inline;' alt=':mouse:'>")
	BBCode = Replace(BBCode,":olympics:","<img src='http://www.skylords.com/img/t/olympics.gif'  style='display:inline;' alt=':olympics:'>")
	BBCode = Replace(BBCode,":pig:","<img src='http://www.skylords.com/img/t/pig.gif'  style='display:inline;' alt=':pig:'>")
	BBCode = Replace(BBCode,":race:","<img src='http://www.skylords.com/img/t/race.gif'  style='display:inline;' alt=':race:'>")
	BBCode = Replace(BBCode,":shrug:","<img src='http://www.skylords.com/img/t/shrug.gif'  style='display:inline;' alt=':shrug:'>")
	BBCode = Replace(BBCode,":sly:","<img src='http://www.skylords.com/img/t/sly.gif'  style='display:inline;' alt=':sly:'>")
	BBCode = Replace(BBCode,":squirrel:","<img src='http://www.skylords.com/img/t/squirrel.gif'  style='display:inline;' alt=':squirrel:'>")
	BBCode = Replace(BBCode,"[b]","<b>")
	BBCode = Replace(BBCode,"[/b]","</b>")
	BBCode = Replace(BBCode,"[i]","<i>")
	BBCode = Replace(BBCode,"[/i]","</i>")
	BBCode = Replace(BBCode,"[u]","<u>")
	BBCode = Replace(BBCode,"[/u]","</u>")
End Function
%>